name: On Particular File Push

on:
  push:
    branches: main
    paths:
      - "**/*.html"

jobs:
  greet:
   runs-on: ubuntu-latest
   steps:
     - name: After HTML Chnage this will Run 
       run: echo "HTML file has been changed "
    




 